export type SyncStatus = 'draft' | 'pending' | 'syncing' | 'synced' | 'error' | 'conflict'
export type EntityType = 'incident' | 'stop' | 'offender' | 'link' | 'photo'
export type Operation = 'create' | 'update' | 'delete' | 'upload'
export type UserRole = 'agent' | 'supervisor' | 'administrator'
export type IncidentType = 'theft' | 'robbery' | 'vandalism' | 'in_flagrante' | 'suspicious' | 'other'
export type IncidentStatus = 'open' | 'in_progress' | 'closed' | 'archived'
export type StopType = 'stop' | 'in_flagrante'
export type StopOutcome = 'released' | 'detained' | 'referred_to_police_station' | 'items_seized' | 'other'
