-- =============================================
-- SIGOP — 008 Seed: municipalities and territorial areas (AT)
-- Run in the Supabase SQL Editor AFTER 007_territorial_areas.sql
-- Naming standard: English (snake_case) — see 003 header note.
--
-- Source: operational list provided by the client (município + 2-letter AT
-- code). Names are kept exactly as supplied (uppercase, no accents). AT
-- `name` and `code` both hold the 2-letter code. All municipalities are in SP.
--
-- Idempotent: ON CONFLICT DO NOTHING on both unique keys
-- (municipalities.name+state, territorial_areas.municipality_id+name).
-- =============================================

-- ---------------------------------------------------------------------------
-- 1. Municipalities
-- ---------------------------------------------------------------------------
INSERT INTO municipalities (name, state) VALUES
  ('ARUJA', 'SP'),
  ('BIRITIBA-MIRIM', 'SP'),
  ('DIADEMA', 'SP'),
  ('FERRAZ DE VASCONCELOS', 'SP'),
  ('GUARAREMA', 'SP'),
  ('GUARULHOS', 'SP'),
  ('ITAQUAQUECETUBA', 'SP'),
  ('MAUA', 'SP'),
  ('MOGI DAS CRUZES', 'SP'),
  ('POA', 'SP'),
  ('RIBEIRAO PIRES', 'SP'),
  ('SANTO ANDRE', 'SP'),
  ('SAO BERNARDO DO CAMPO', 'SP'),
  ('SAO CAETANO DO SUL', 'SP'),
  ('SAO PAULO', 'SP'),
  ('SUZANO', 'SP')
ON CONFLICT (name, state) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Territorial areas (AT) — one row per município + code pair
-- ---------------------------------------------------------------------------
INSERT INTO territorial_areas (municipality_id, name, code)
SELECT m.id, v.code, v.code
FROM (VALUES
  ('ARUJA', 'AJ'),
  ('ARUJA', 'AO'),
  ('BIRITIBA-MIRIM', 'BM'),
  ('DIADEMA', 'BE'),
  ('DIADEMA', 'BG'),
  ('DIADEMA', 'DD'),
  ('DIADEMA', 'PM'),
  ('DIADEMA', 'VD'),
  ('FERRAZ DE VASCONCELOS', 'FV'),
  ('GUARAREMA', 'GM'),
  ('GUARULHOS', 'AO'),
  ('GUARULHOS', 'BO'),
  ('GUARULHOS', 'CC'),
  ('GUARULHOS', 'DU'),
  ('GUARULHOS', 'GR'),
  ('GUARULHOS', 'MQ'),
  ('GUARULHOS', 'NA'),
  ('GUARULHOS', 'NB'),
  ('GUARULHOS', 'PC'),
  ('GUARULHOS', 'PG'),
  ('ITAQUAQUECETUBA', 'BS'),
  ('ITAQUAQUECETUBA', 'ID'),
  ('ITAQUAQUECETUBA', 'IT'),
  ('ITAQUAQUECETUBA', 'VJ'),
  ('MAUA', 'AB'),
  ('MAUA', 'JI'),
  ('MAUA', 'MA'),
  ('MAUA', 'PJ'),
  ('MAUA', 'SM'),
  ('MOGI DAS CRUZES', 'BC'),
  ('MOGI DAS CRUZES', 'JP'),
  ('MOGI DAS CRUZES', 'MO'),
  ('MOGI DAS CRUZES', 'PG'),
  ('POA', 'PA'),
  ('RIBEIRAO PIRES', 'RP'),
  ('SANTO ANDRE', 'CM'),
  ('SANTO ANDRE', 'CP'),
  ('SANTO ANDRE', 'HT'),
  ('SANTO ANDRE', 'PI'),
  ('SANTO ANDRE', 'PO'),
  ('SANTO ANDRE', 'PS'),
  ('SANTO ANDRE', 'SA'),
  ('SANTO ANDRE', 'ST'),
  ('SANTO ANDRE', 'UT'),
  ('SANTO ANDRE', 'VM'),
  ('SAO BERNARDO DO CAMPO', 'AS'),
  ('SAO BERNARDO DO CAMPO', 'BA'),
  ('SAO BERNARDO DO CAMPO', 'CB'),
  ('SAO BERNARDO DO CAMPO', 'DM'),
  ('SAO BERNARDO DO CAMPO', 'FZ'),
  ('SAO BERNARDO DO CAMPO', 'PL'),
  ('SAO BERNARDO DO CAMPO', 'RG'),
  ('SAO BERNARDO DO CAMPO', 'RR'),
  ('SAO BERNARDO DO CAMPO', 'SB'),
  ('SAO BERNARDO DO CAMPO', 'VP'),
  ('SAO CAETANO DO SUL', 'SC'),
  ('SAO CAETANO DO SUL', 'TM'),
  ('SAO CAETANO DO SUL', 'VG'),
  ('SAO PAULO', 'AC'),
  ('SAO PAULO', 'AD'),
  ('SAO PAULO', 'AF'),
  ('SAO PAULO', 'AM'),
  ('SAO PAULO', 'AN'),
  ('SAO PAULO', 'AR'),
  ('SAO PAULO', 'AS'),
  ('SAO PAULO', 'BC'),
  ('SAO PAULO', 'BI'),
  ('SAO PAULO', 'BR'),
  ('SAO PAULO', 'CA'),
  ('SAO PAULO', 'CE'),
  ('SAO PAULO', 'CG'),
  ('SAO PAULO', 'CI'),
  ('SAO PAULO', 'CN'),
  ('SAO PAULO', 'CO'),
  ('SAO PAULO', 'CT'),
  ('SAO PAULO', 'CV'),
  ('SAO PAULO', 'DT'),
  ('SAO PAULO', 'ED'),
  ('SAO PAULO', 'EM'),
  ('SAO PAULO', 'GU'),
  ('SAO PAULO', 'GZ'),
  ('SAO PAULO', 'HM'),
  ('SAO PAULO', 'IA'),
  ('SAO PAULO', 'IB'),
  ('SAO PAULO', 'IG'),
  ('SAO PAULO', 'IM'),
  ('SAO PAULO', 'IN'),
  ('SAO PAULO', 'IP'),
  ('SAO PAULO', 'IR'),
  ('SAO PAULO', 'IT'),
  ('SAO PAULO', 'JA'),
  ('SAO PAULO', 'JB'),
  ('SAO PAULO', 'JC'),
  ('SAO PAULO', 'JD'),
  ('SAO PAULO', 'JF'),
  ('SAO PAULO', 'JI'),
  ('SAO PAULO', 'JL'),
  ('SAO PAULO', 'JM'),
  ('SAO PAULO', 'LI'),
  ('SAO PAULO', 'LM'),
  ('SAO PAULO', 'LV'),
  ('SAO PAULO', 'LZ'),
  ('SAO PAULO', 'ME'),
  ('SAO PAULO', 'MO'),
  ('SAO PAULO', 'MY'),
  ('SAO PAULO', 'NC'),
  ('SAO PAULO', 'NP'),
  ('SAO PAULO', 'OR'),
  ('SAO PAULO', 'PA'),
  ('SAO PAULO', 'PD'),
  ('SAO PAULO', 'PE'),
  ('SAO PAULO', 'PF'),
  ('SAO PAULO', 'PI'),
  ('SAO PAULO', 'PM'),
  ('SAO PAULO', 'PR'),
  ('SAO PAULO', 'RB'),
  ('SAO PAULO', 'RR'),
  ('SAO PAULO', 'SD'),
  ('SAO PAULO', 'SF'),
  ('SAO PAULO', 'SI'),
  ('SAO PAULO', 'SM'),
  ('SAO PAULO', 'SS'),
  ('SAO PAULO', 'ST'),
  ('SAO PAULO', 'SZ'),
  ('SAO PAULO', 'TE'),
  ('SAO PAULO', 'TI'),
  ('SAO PAULO', 'TR'),
  ('SAO PAULO', 'VA'),
  ('SAO PAULO', 'VE'),
  ('SAO PAULO', 'VG'),
  ('SAO PAULO', 'VL'),
  ('SAO PAULO', 'VM'),
  ('SAO PAULO', 'VP'),
  ('SAO PAULO', 'VT'),
  ('SAO PAULO', 'VU'),
  ('SAO PAULO', 'ZE'),
  ('SUZANO', 'BP'),
  ('SUZANO', 'SZ'),
  ('SUZANO', 'VE')
) AS v(muni, code)
JOIN municipalities m ON m.name = v.muni AND m.state = 'SP'
ON CONFLICT (municipality_id, name) DO NOTHING;
