-- =============================================
-- SIGOP — 012 Seed: contractors and their territorial areas (AT)
-- Run in the Supabase SQL Editor AFTER 011_contractors.sql
-- Naming standard: English (snake_case) — see 003 header note.
--
-- Source: two operational lists provided by the client.
--   - West / São José dos Campos region: entirely new municípios + ATs,
--     under contractors ABILITY_OS and ABILITY_SJ.
--   - ABC / São Paulo region: the 16 municípios already seeded in 008,
--     whose ATs had no contractor yet — this backfills contractor_id for
--     them, split across 5 contractors (ICOMON_CENTRO/JD/LESTE/ABCD/AT).
-- Município names are kept accent-free / uppercase, matching the existing
-- 008 convention (e.g. "ARAÇARIGUAMA" -> "ARACARIGUAMA"), so names match
-- exactly between the two source lists and against the 008 seed.
--
-- Idempotent: ON CONFLICT DO NOTHING / DO UPDATE against the existing
-- unique keys (contractors.name, municipalities.name+state,
-- territorial_areas.municipality_id+name).
-- =============================================

-- ---------------------------------------------------------------------------
-- 1. Contractors
-- ---------------------------------------------------------------------------
INSERT INTO contractors (name) VALUES
  ('ABILITY_OS'),
  ('ABILITY_SJ'),
  ('ICOMON_CENTRO'),
  ('ICOMON_JD'),
  ('ICOMON_LESTE'),
  ('ICOMON_ABCD'),
  ('ICOMON_AT')
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. West / SJC region — new municípios
-- ---------------------------------------------------------------------------
INSERT INTO municipalities (name, state) VALUES
  ('ALUMINIO', 'SP'),
  ('ARACARIGUAMA', 'SP'),
  ('BARUERI', 'SP'),
  ('CARAPICUIBA', 'SP'),
  ('COTIA', 'SP'),
  ('EMBU', 'SP'),
  ('EMBU-GUACU', 'SP'),
  ('ITAPECERICA DA SERRA', 'SP'),
  ('ITAPEVI', 'SP'),
  ('JANDIRA', 'SP'),
  ('JUQUITIBA', 'SP'),
  ('MAIRINQUE', 'SP'),
  ('OSASCO', 'SP'),
  ('PIRAPORA DO BOM JESUS', 'SP'),
  ('SANTANA DE PARNAIBA', 'SP'),
  ('SAO LOURENCO DA SERRA', 'SP'),
  ('SAO ROQUE', 'SP'),
  ('TABOAO DA SERRA', 'SP'),
  ('VARGEM GRANDE PAULISTA', 'SP'),
  ('SANTA BRANCA', 'SP'),
  ('NATIVIDADE DA SERRA', 'SP'),
  ('APARECIDA', 'SP'),
  ('ARAPEI', 'SP'),
  ('AREIAS', 'SP'),
  ('BANANAL', 'SP'),
  ('CACAPAVA', 'SP'),
  ('CACHOEIRA PAULISTA', 'SP'),
  ('CAMPOS DO JORDAO', 'SP'),
  ('CANAS', 'SP'),
  ('CARAGUATATUBA', 'SP'),
  ('CRUZEIRO', 'SP'),
  ('CUNHA', 'SP'),
  ('GUARATINGUETA', 'SP'),
  ('ILHABELA', 'SP'),
  ('JACAREI', 'SP'),
  ('JAMBEIRO', 'SP'),
  ('LAGOINHA', 'SP'),
  ('LAVRINHAS', 'SP'),
  ('LORENA', 'SP'),
  ('PARAIBUNA', 'SP'),
  ('PINDAMONHANGABA', 'SP'),
  ('PIQUETE', 'SP'),
  ('POTIM', 'SP'),
  ('QUELUZ', 'SP'),
  ('REDENCAO DA SERRA', 'SP'),
  ('ROSEIRA', 'SP'),
  ('SANTO ANTONIO DO PINHAL', 'SP'),
  ('SAO BENTO DO SAPUCAI', 'SP'),
  ('SAO JOSE DO BARREIRO', 'SP'),
  ('SAO JOSE DOS CAMPOS', 'SP'),
  ('SAO LUIS DO PARAITINGA', 'SP'),
  ('SAO SEBASTIAO', 'SP'),
  ('SILVEIRAS', 'SP'),
  ('TAUBATE', 'SP'),
  ('TREMEMBE', 'SP'),
  ('UBATUBA', 'SP')
ON CONFLICT (name, state) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. West / SJC region — territorial areas (AT), linked to their contractor
-- ---------------------------------------------------------------------------
INSERT INTO territorial_areas (municipality_id, name, code, contractor_id)
SELECT m.id, v.code, v.code, c.id
FROM (VALUES
  ('ALUMINIO', 'AU', 'ABILITY_OS'),
  ('ALUMINIO', 'PG', 'ABILITY_OS'),
  ('ARACARIGUAMA', 'AG', 'ABILITY_OS'),
  ('ARACARIGUAMA', 'VO', 'ABILITY_OS'),
  ('BARUERI', 'AS', 'ABILITY_OS'),
  ('BARUERI', 'AL', 'ABILITY_OS'),
  ('BARUERI', 'BA', 'ABILITY_OS'),
  ('BARUERI', 'CN', 'ABILITY_OS'),
  ('BARUERI', 'JS', 'ABILITY_OS'),
  ('CARAPICUIBA', 'AD', 'ABILITY_OS'),
  ('CARAPICUIBA', 'AT', 'ABILITY_OS'),
  ('CARAPICUIBA', 'CA', 'ABILITY_OS'),
  ('CARAPICUIBA', 'VD', 'ABILITY_OS'),
  ('CARAPICUIBA', 'VI', 'ABILITY_OS'),
  ('COTIA', 'CI', 'ABILITY_OS'),
  ('COTIA', 'GJ', 'ABILITY_OS'),
  ('COTIA', 'CT', 'ABILITY_OS'),
  ('EMBU', 'EB', 'ABILITY_OS'),
  ('EMBU', 'PI', 'ABILITY_OS'),
  ('EMBU', 'SE', 'ABILITY_OS'),
  ('EMBU-GUACU', 'CO', 'ABILITY_OS'),
  ('EMBU-GUACU', 'EG', 'ABILITY_OS'),
  ('EMBU-GUACU', 'PA', 'ABILITY_OS'),
  ('ITAPECERICA DA SERRA', 'CM', 'ABILITY_OS'),
  ('ITAPECERICA DA SERRA', 'IS', 'ABILITY_OS'),
  ('ITAPECERICA DA SERRA', 'PU', 'ABILITY_OS'),
  ('ITAPEVI', 'AB', 'ABILITY_OS'),
  ('ITAPEVI', 'IV', 'ABILITY_OS'),
  ('ITAPEVI', 'QE', 'ABILITY_OS'),
  ('JANDIRA', 'JA', 'ABILITY_OS'),
  ('JANDIRA', 'SF', 'ABILITY_OS'),
  ('JUQUITIBA', 'BB', 'ABILITY_OS'),
  ('JUQUITIBA', 'JQ', 'ABILITY_OS'),
  ('JUQUITIBA', 'PL', 'ABILITY_OS'),
  ('MAIRINQUE', 'MQ', 'ABILITY_OS'),
  ('MAIRINQUE', 'PO', 'ABILITY_OS'),
  ('OSASCO', 'MK', 'ABILITY_OS'),
  ('OSASCO', 'OS', 'ABILITY_OS'),
  ('OSASCO', 'QT', 'ABILITY_OS'),
  ('OSASCO', 'RO', 'ABILITY_OS'),
  ('OSASCO', 'SN', 'ABILITY_OS'),
  ('PIRAPORA DO BOM JESUS', 'CK', 'ABILITY_OS'),
  ('PIRAPORA DO BOM JESUS', 'PJ', 'ABILITY_OS'),
  ('SANTANA DE PARNAIBA', 'AS', 'ABILITY_OS'),
  ('SANTANA DE PARNAIBA', 'AP', 'ABILITY_OS'),
  ('SANTANA DE PARNAIBA', 'CB', 'ABILITY_OS'),
  ('SANTANA DE PARNAIBA', 'CL', 'ABILITY_OS'),
  ('SANTANA DE PARNAIBA', 'DV', 'ABILITY_OS'),
  ('SANTANA DE PARNAIBA', 'SP', 'ABILITY_OS'),
  ('SANTANA DE PARNAIBA', 'VN', 'ABILITY_OS'),
  ('SAO LOURENCO DA SERRA', 'SL', 'ABILITY_OS'),
  ('SAO ROQUE', 'AE', 'ABILITY_OS'),
  ('SAO ROQUE', 'CG', 'ABILITY_OS'),
  ('SAO ROQUE', 'PC', 'ABILITY_OS'),
  ('SAO ROQUE', 'PN', 'ABILITY_OS'),
  ('SAO ROQUE', 'RV', 'ABILITY_OS'),
  ('SAO ROQUE', 'SR', 'ABILITY_OS'),
  ('SAO ROQUE', 'SE', 'ABILITY_OS'),
  ('SAO ROQUE', 'SA', 'ABILITY_OS'),
  ('TABOAO DA SERRA', 'TA', 'ABILITY_OS'),
  ('TABOAO DA SERRA', 'TK', 'ABILITY_OS'),
  ('VARGEM GRANDE PAULISTA', 'VT', 'ABILITY_OS'),

  ('SANTA BRANCA', 'RC', 'ABILITY_SJ'),
  ('NATIVIDADE DA SERRA', 'PA', 'ABILITY_SJ'),
  ('APARECIDA', 'CT', 'ABILITY_SJ'),
  ('ARAPEI', 'AR', 'ABILITY_SJ'),
  ('AREIAS', 'JC', 'ABILITY_SJ'),
  ('BANANAL', 'RJ', 'ABILITY_SJ'),
  ('CACAPAVA', 'MI', 'ABILITY_SJ'),
  ('CACHOEIRA PAULISTA', 'CD', 'ABILITY_SJ'),
  ('CACHOEIRA PAULISTA', 'EB', 'ABILITY_SJ'),
  ('CACHOEIRA PAULISTA', 'QM', 'ABILITY_SJ'),
  ('CAMPOS DO JORDAO', 'AB', 'ABILITY_SJ'),
  ('CAMPOS DO JORDAO', 'ER', 'ABILITY_SJ'),
  ('CANAS', 'CS', 'ABILITY_SJ'),
  ('CARAGUATATUBA', 'AA', 'ABILITY_SJ'),
  ('CARAGUATATUBA', 'MG', 'ABILITY_SJ'),
  ('CARAGUATATUBA', 'PN', 'ABILITY_SJ'),
  ('CARAGUATATUBA', 'MK', 'ABILITY_SJ'),
  ('CRUZEIRO', 'NR', 'ABILITY_SJ'),
  ('CUNHA', 'PG', 'ABILITY_SJ'),
  ('CUNHA', 'BP', 'ABILITY_SJ'),
  ('CUNHA', 'CC', 'ABILITY_SJ'),
  ('GUARATINGUETA', 'PD', 'ABILITY_SJ'),
  ('GUARATINGUETA', 'MF', 'ABILITY_SJ'),
  ('GUARATINGUETA', 'NG', 'ABILITY_SJ'),
  ('GUARATINGUETA', 'RC', 'ABILITY_SJ'),
  ('ILHABELA', 'BV', 'ABILITY_SJ'),
  ('ILHABELA', 'FM', 'ABILITY_SJ'),
  ('ILHABELA', 'RP', 'ABILITY_SJ'),
  ('ILHABELA', 'CQ', 'ABILITY_SJ'),
  ('ILHABELA', 'PR', 'ABILITY_SJ'),
  ('JACAREI', 'CF', 'ABILITY_SJ'),
  ('JACAREI', 'JM', 'ABILITY_SJ'),
  ('JACAREI', 'LN', 'ABILITY_SJ'),
  ('JACAREI', 'SS', 'ABILITY_SJ'),
  ('JAMBEIRO', 'DB', 'ABILITY_SJ'),
  ('LAGOINHA', 'CA', 'ABILITY_SJ'),
  ('LAGOINHA', 'MC', 'ABILITY_SJ'),
  ('LAVRINHAS', 'CH', 'ABILITY_SJ'),
  ('LORENA', 'VA', 'ABILITY_SJ'),
  ('NATIVIDADE DA SERRA', 'TA', 'ABILITY_SJ'),
  ('NATIVIDADE DA SERRA', 'BA', 'ABILITY_SJ'),
  ('PARAIBUNA', 'DC', 'ABILITY_SJ'),
  ('PARAIBUNA', 'SG', 'ABILITY_SJ'),
  ('PARAIBUNA', 'BF', 'ABILITY_SJ'),
  ('PINDAMONHANGABA', 'MC', 'ABILITY_SJ'),
  ('PINDAMONHANGABA', 'LM', 'ABILITY_SJ'),
  ('PIQUETE', 'LR', 'ABILITY_SJ'),
  ('POTIM', 'PO', 'ABILITY_SJ'),
  ('QUELUZ', 'ME', 'ABILITY_SJ'),
  ('REDENCAO DA SERRA', 'RN', 'ABILITY_SJ'),
  ('ROSEIRA', 'DE', 'ABILITY_SJ'),
  ('SANTA BRANCA', 'AL', 'ABILITY_SJ'),
  ('SANTA BRANCA', 'SB', 'ABILITY_SJ'),
  ('SANTA BRANCA', 'NJ', 'ABILITY_SJ'),
  ('SANTO ANTONIO DO PINHAL', 'FM', 'ABILITY_SJ'),
  ('SAO BENTO DO SAPUCAI', 'RA', 'ABILITY_SJ'),
  ('SAO BENTO DO SAPUCAI', 'QI', 'ABILITY_SJ'),
  ('SAO JOSE DO BARREIRO', 'SR', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'BE', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'BQ', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'CA', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'EB', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'EM', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'RH', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'JS', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'RD', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'NH', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'PT', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'SI', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'TT', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'UR', 'ABILITY_SJ'),
  ('SAO JOSE DOS CAMPOS', 'FX', 'ABILITY_SJ'),
  ('SAO LUIS DO PARAITINGA', 'DC', 'ABILITY_SJ'),
  ('SAO LUIS DO PARAITINGA', 'CT', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'AC', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'BA', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'GU', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'TQ', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'EN', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'FP', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'BU', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'BO', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'BC', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'MR', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'PB', 'ABILITY_SJ'),
  ('SAO SEBASTIAO', 'PJ', 'ABILITY_SJ'),
  ('SILVEIRAS', 'RS', 'ABILITY_SJ'),
  ('SILVEIRAS', 'PB', 'ABILITY_SJ'),
  ('SILVEIRAS', 'MA', 'ABILITY_SJ'),
  ('TAUBATE', 'QM', 'ABILITY_SJ'),
  ('TAUBATE', 'XV', 'ABILITY_SJ'),
  ('TAUBATE', 'AM', 'ABILITY_SJ'),
  ('TAUBATE', 'BR', 'ABILITY_SJ'),
  ('TAUBATE', 'CN', 'ABILITY_SJ'),
  ('TAUBATE', 'EB', 'ABILITY_SJ'),
  ('TAUBATE', 'IN', 'ABILITY_SJ'),
  ('TAUBATE', 'SJ', 'ABILITY_SJ'),
  ('TREMEMBE', 'SB', 'ABILITY_SJ'),
  ('TREMEMBE', 'PE', 'ABILITY_SJ'),
  ('UBATUBA', 'IT', 'ABILITY_SJ'),
  ('UBATUBA', 'LG', 'ABILITY_SJ'),
  ('UBATUBA', 'MA', 'ABILITY_SJ'),
  ('UBATUBA', 'LZ', 'ABILITY_SJ'),
  ('UBATUBA', 'PG', 'ABILITY_SJ'),
  ('UBATUBA', 'PV', 'ABILITY_SJ'),
  ('UBATUBA', 'TG', 'ABILITY_SJ'),
  ('UBATUBA', 'PC', 'ABILITY_SJ')
) AS v(municipality_name, code, contractor_name)
JOIN municipalities m ON m.name = v.municipality_name AND m.state = 'SP'
JOIN contractors c ON c.name = v.contractor_name
ON CONFLICT (municipality_id, name) DO UPDATE SET contractor_id = EXCLUDED.contractor_id;

-- ---------------------------------------------------------------------------
-- 4. ABC / SP region — backfill contractor_id on the 16 municípios already
--    seeded in 008 (their territorial_areas rows already exist; this creates
--    any missing ones and sets contractor_id on all of them either way).
-- ---------------------------------------------------------------------------
INSERT INTO territorial_areas (municipality_id, name, code, contractor_id)
SELECT m.id, v.code, v.code, c.id
FROM (VALUES
  ('SAO PAULO', 'IP', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'IM', 'ICOMON_JD'),
  ('SAO PAULO', 'PE', 'ICOMON_LESTE'),
  ('SAO PAULO', 'JA', 'ICOMON_LESTE'),
  ('DIADEMA', 'BE', 'ICOMON_ABCD'),
  ('SAO PAULO', 'JC', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'AN', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'SS', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'CI', 'ICOMON_LESTE'),
  ('GUARULHOS', 'NB', 'ICOMON_LESTE'),
  ('SAO PAULO', 'TI', 'ICOMON_LESTE'),
  ('SAO PAULO', 'ED', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'HM', 'ICOMON_JD'),
  ('SAO PAULO', 'NC', 'ICOMON_LESTE'),
  ('SAO PAULO', 'PR', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'EM', 'ICOMON_LESTE'),
  ('DIADEMA', 'BG', 'ICOMON_ABCD'),
  ('SAO PAULO', 'SZ', 'ICOMON_LESTE'),
  ('SAO PAULO', 'ST', 'ICOMON_LESTE'),
  ('SANTO ANDRE', 'SA', 'ICOMON_ABCD'),
  ('SAO PAULO', 'DT', 'ICOMON_LESTE'),
  ('SAO PAULO', 'CO', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'JL', 'ICOMON_LESTE'),
  ('SAO PAULO', 'VM', 'ICOMON_JD'),
  ('SAO PAULO', 'LZ', 'ICOMON_LESTE'),
  ('GUARULHOS', 'GR', 'ICOMON_LESTE'),
  ('SAO PAULO', 'GU', 'ICOMON_CENTRO'),
  ('SAO CAETANO DO SUL', 'SC', 'ICOMON_ABCD'),
  ('SAO CAETANO DO SUL', 'VG', 'ICOMON_ABCD'),
  ('MOGI DAS CRUZES', 'BC', 'ICOMON_AT'),
  ('ITAQUAQUECETUBA', 'BS', 'ICOMON_AT'),
  ('ARUJA', 'AJ', 'ICOMON_AT'),
  ('SAO PAULO', 'PF', 'ICOMON_LESTE'),
  ('SAO BERNARDO DO CAMPO', 'SB', 'ICOMON_ABCD'),
  ('SAO PAULO', 'BC', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'IA', 'ICOMON_LESTE'),
  ('MAUA', 'JI', 'ICOMON_AT'),
  ('FERRAZ DE VASCONCELOS', 'FV', 'ICOMON_AT'),
  ('SAO PAULO', 'TR', 'ICOMON_LESTE'),
  ('SAO PAULO', 'JD', 'ICOMON_JD'),
  ('SAO PAULO', 'SI', 'ICOMON_CENTRO'),
  ('DIADEMA', 'VD', 'ICOMON_ABCD'),
  ('MAUA', 'MA', 'ICOMON_AT'),
  ('SAO PAULO', 'AS', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'GZ', 'ICOMON_LESTE'),
  ('POA', 'PA', 'ICOMON_AT'),
  ('SAO BERNARDO DO CAMPO', 'BA', 'ICOMON_ABCD'),
  ('SAO PAULO', 'CV', 'ICOMON_LESTE'),
  ('SAO PAULO', 'IT', 'ICOMON_LESTE'),
  ('SAO PAULO', 'AD', 'ICOMON_CENTRO'),
  ('GUARULHOS', 'MQ', 'ICOMON_LESTE'),
  ('GUARULHOS', 'CC', 'ICOMON_LESTE'),
  ('SAO PAULO', 'CN', 'ICOMON_LESTE'),
  ('DIADEMA', 'DD', 'ICOMON_ABCD'),
  ('GUARULHOS', 'NA', 'ICOMON_LESTE'),
  ('MOGI DAS CRUZES', 'JP', 'ICOMON_AT'),
  ('SAO PAULO', 'VE', 'ICOMON_LESTE'),
  ('SAO PAULO', 'VL', 'ICOMON_LESTE'),
  ('SAO PAULO', 'LM', 'ICOMON_LESTE'),
  ('SANTO ANDRE', 'CP', 'ICOMON_ABCD'),
  ('SAO PAULO', 'LI', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'IR', 'ICOMON_LESTE'),
  ('SAO PAULO', 'MY', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'IG', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'IN', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'BR', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'VU', 'ICOMON_LESTE'),
  ('ITAQUAQUECETUBA', 'ID', 'ICOMON_AT'),
  ('SAO BERNARDO DO CAMPO', 'FZ', 'ICOMON_ABCD'),
  ('GUARULHOS', 'PG', 'ICOMON_LESTE'),
  ('SUZANO', 'VE', 'ICOMON_AT'),
  ('SAO PAULO', 'IB', 'ICOMON_JD'),
  ('SAO PAULO', 'AM', 'ICOMON_CENTRO'),
  ('GUARULHOS', 'BO', 'ICOMON_LESTE'),
  ('SAO PAULO', 'VT', 'ICOMON_LESTE'),
  ('SAO PAULO', 'JM', 'ICOMON_CENTRO'),
  ('SAO BERNARDO DO CAMPO', 'RR', 'ICOMON_ABCD'),
  ('SAO BERNARDO DO CAMPO', 'AS', 'ICOMON_ABCD'),
  ('SAO PAULO', 'OR', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'JF', 'ICOMON_LESTE'),
  ('SAO PAULO', 'PM', 'ICOMON_LESTE'),
  ('RIBEIRAO PIRES', 'RP', 'ICOMON_AT'),
  ('MOGI DAS CRUZES', 'MO', 'ICOMON_AT'),
  ('SUZANO', 'SZ', 'ICOMON_AT'),
  ('SAO PAULO', 'AC', 'ICOMON_CENTRO'),
  ('GUARULHOS', 'PC', 'ICOMON_LESTE'),
  ('MAUA', 'AB', 'ICOMON_AT'),
  ('SAO PAULO', 'PA', 'ICOMON_JD'),
  ('SAO PAULO', 'CG', 'ICOMON_CENTRO'),
  ('ITAQUAQUECETUBA', 'VJ', 'ICOMON_AT'),
  ('SANTO ANDRE', 'PS', 'ICOMON_ABCD'),
  ('SAO PAULO', 'PI', 'ICOMON_JD'),
  ('SANTO ANDRE', 'ST', 'ICOMON_ABCD'),
  ('SAO PAULO', 'JB', 'ICOMON_CENTRO'),
  ('GUARULHOS', 'DU', 'ICOMON_LESTE'),
  ('SAO BERNARDO DO CAMPO', 'PL', 'ICOMON_ABCD'),
  ('ARUJA', 'AO', 'ICOMON_AT'),
  ('SAO PAULO', 'LV', 'ICOMON_CENTRO'),
  ('SAO BERNARDO DO CAMPO', 'CB', 'ICOMON_ABCD'),
  ('GUARULHOS', 'AO', 'ICOMON_LESTE'),
  ('DIADEMA', 'PM', 'ICOMON_ABCD'),
  ('GUARAREMA', 'GM', 'ICOMON_AT'),
  ('SAO PAULO', 'PD', 'ICOMON_JD'),
  ('SAO PAULO', 'NP', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'VA', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'ME', 'ICOMON_JD'),
  ('SAO PAULO', 'AR', 'ICOMON_LESTE'),
  ('SAO PAULO', 'JI', 'ICOMON_LESTE'),
  ('SANTO ANDRE', 'HT', 'ICOMON_ABCD'),
  ('SAO PAULO', 'VG', 'ICOMON_LESTE'),
  ('SAO PAULO', 'SF', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'BI', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'SD', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'CA', 'ICOMON_LESTE'),
  ('ITAQUAQUECETUBA', 'IT', 'ICOMON_AT'),
  ('SANTO ANDRE', 'PO', 'ICOMON_ABCD'),
  ('SAO PAULO', 'CE', 'ICOMON_CENTRO'),
  ('MOGI DAS CRUZES', 'PG', 'ICOMON_AT'),
  ('SANTO ANDRE', 'PI', 'ICOMON_ABCD'),
  ('SAO BERNARDO DO CAMPO', 'VP', 'ICOMON_ABCD'),
  ('SAO PAULO', 'CT', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'RB', 'ICOMON_LESTE'),
  ('SAO PAULO', 'ZE', 'ICOMON_CENTRO'),
  ('SANTO ANDRE', 'VM', 'ICOMON_ABCD'),
  ('SAO PAULO', 'MO', 'ICOMON_CENTRO'),
  ('SAO BERNARDO DO CAMPO', 'RG', 'ICOMON_ABCD'),
  ('SAO BERNARDO DO CAMPO', 'DM', 'ICOMON_ABCD'),
  ('SAO PAULO', 'SM', 'ICOMON_LESTE'),
  ('MAUA', 'PJ', 'ICOMON_AT'),
  ('MAUA', 'SM', 'ICOMON_AT'),
  ('SAO PAULO', 'RR', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'VP', 'ICOMON_CENTRO'),
  ('BIRITIBA-MIRIM', 'BM', 'ICOMON_AT'),
  ('SAO CAETANO DO SUL', 'TM', 'ICOMON_ABCD'),
  ('SANTO ANDRE', 'UT', 'ICOMON_ABCD'),
  ('SUZANO', 'BP', 'ICOMON_AT'),
  ('SANTO ANDRE', 'CM', 'ICOMON_ABCD'),
  ('SAO PAULO', 'TE', 'ICOMON_CENTRO'),
  ('SAO PAULO', 'AF', 'ICOMON_CENTRO')
) AS v(municipality_name, code, contractor_name)
JOIN municipalities m ON m.name = v.municipality_name AND m.state = 'SP'
JOIN contractors c ON c.name = v.contractor_name
ON CONFLICT (municipality_id, name) DO UPDATE SET contractor_id = EXCLUDED.contractor_id;
